<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <AssemblyName>caller</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../fixture/fixture.csproj" />
    <ProjectReference Include="../libA/libA.csproj" />
    <ProjectReference Include="../libB/libB.csproj" />
  </ItemGroup>
</Project>
